product: wow

ignored: [
	7,    # Gray Wolf
	15,   # Winter Wolf
	28,   # Skeletal Horse
	70,   # Riding Kodo
	123,  # Nether Drake
	238,  # Swift Spectral Gryphon
	251,  # Black Polar Bear
	273,  # Grand Caravan Mammoth
	274,  # Grand Caravan Mammoth
	308,  # Blue Skeletal Warhorse
	462,  # White Riding Yak
	484,  # Black Riding Yak
	485,  # Brown Riding Yak
	776,  # Swift Spectral Rylak
	786,  # Charger
	934,  # Swift Spectral Hippogryph
	987,  # Valorous Charger
	989,  # Vengeful Charger
	990,  # Vigilant Charger
	991,  # Golden Charger
	1269, # Swift Spectral Fathom Ray (inv_mount_hippogryph_arcane)
	1270, # Swift Spectral Magnetocraft (inv_mount_hippogryph_arcane)
	1271, # Swift Spectral Armored Gryphon (inv_mount_hippogryph_arcane)
	1272, # Swift Spectral Pterrordax (inv_mount_hippogryph_arcane)
	1578, # [DND] Test Mount JZB (ability_mount_travellersyakmount)
	1605, # Dragon Isles Drake Model Test
	1607, # Swift Spectral Drake
	1608, # Soar, Dracthyr racial
]

# family based on http://www.warcraftmounts.com/gallery.php + https://wow.gamepedia.com/Beast
# try to keep naming in singular
familymap: [
  { name: Amphibian,
    subfamily: [
      {name: Crawgs, wcm: [Crawgs]},
			{name: Toads, wcm: [Toads]},
		]
	},
  { name: Arachnids,
    subfamily: [
      {name: Blood Ticks, wcm: [Bloodswarmers]},
			{name: Scorpions, wcm: [Scorpions, Mechanical Scorpions]},
			{name: Spiders, wcm: [Spiders]},
		]
	},
	{ name: Bats, wcm: [Bats, Felbats] },
  { name: Birds,
    subfamily: [
      {name: Albatross, wcm: [Birds], icons: [alabatross, albatross]},
      {name: Chickens, wcm: [Chickens]},
      {name: Cranes, wcm: [Cranes]},
      {name: Crows, wcm: [Birds], icons: [roguemount, arcaneraven, suncrown]},
      {name: Dread Ravens, wcm: [Birds], icons: [ravenlord, dreadraven]},
			{name: Eagle, wcm: [Birds], icons: [eagle]},
      {name: Hawkstriders, wcm: [Hawkstriders]},
      {name: Mechanical Birds, wcm: [Mechanical Birds]},
      {name: Pandaren Phoenixes, wcm: [Birds], icons: [pandarenphoenix, ji-kun, thunderislebirdboss]},
      {name: Parrots, wcm: [Birds], icons: [parrot]},
      {name: Phoenixes, wcm: [Phoenixes]},
      {name: Raptora, wcm: [Birds], icons: [progenitorhawk]},
      {name: Roc, wcm: [Deathrocs]},
      {name: Tallstriders, wcm: [Tallstriders]},
      {name: Talonbirds, wcm: [Talonbirds]},
      {name: Vultures, wcm: [Birds], icons: [vulture]},
		]
	},
  { name: Bovids,
    subfamily: [
		  {name: Clefthooves, wcm: [Clefthooves]},
			{name: Goats, wcm: [Goats]},
			{name: Rams, wcm: [Rams]},
      {name: Ruinstriders, wcm: [Talbuks], icons: [argustalbukmount, paladin_divinesteed, lightforgedtalbuk]},
      {name: Talbuks, wcm: [Talbuks], icons: [foot_centaur, talbukdraenor]},
      {name: Tauralus, wcm: [Tauraluses]},
      {name: Yaks, wcm: [Yaks]},
		]
	},
	{ name: Carnivorans,
    subfamily: [
      {name: Bears, wcm: [Bears]},
      {name: Foxes, wcm: [Foxes]},
      {name: Gargon, wcm: [Gargons]},
      {name: Hounds, wcm: [Dogs, Core Hounds, Felstalkers, Darkhounds, Soulseekers]},
      {name: Hyenas, wcm: [Hyenas]},
      {name: Quilen, wcm: [Quilen]},
      {name: Vulpin, wcm: [Vulpin]},
      {name: Ottuk, wcm: [Ottuks], ids: [1654]}, # Otterworldly Ottuk Carrier
	]
	},
  { name: Cats,
    subfamily: [
    	{name: Lions, wcm: [Cats], icons: [lion, goldenking], ids: [421]},                     # Winged Guardian
    	{name: Manasabers, wcm: [Cats], icons: [suramarmount, nightborneracial], ids: [741]}, # Mystic Runesaber
    	{name: Mechanical Cats, wcm: [Mechanical Cats]},
    	{name: Others, wcm: [Flamesabers, Panthara, Felsabers, Undead Cats], ids: [1330, 1531, 1576]}, # Sunwarmed Furline, Wen Lo, Jigglesworth Sr.
    	{name: Sabers, wcm: [Cats], icons: [blackpanther, whitetiger, pinktiger, nightsaber2, saber3mount, sabertooth]},
    	{name: Stone Cats, wcm: [Flying Stone Cats], ids: [421]}, # Winged Guardian
    	{name: Tigers, wcm: [Cats, Undead Cats], icons: [monkmount, spectraltiger, siberiantiger, warnightsaber, jungletiger]},
		]
	},
	{name: Crabs, wcm:  [Crabs]},
	{ name: Demons,
    subfamily: [
		  {name: Demonic Hounds, wcm: [Felstalkers, Vile Fiends, Antoran Hounds, Flying Felstalkers]},
		  {name: Demonic Steeds, wcm: [Demonic Steeds]},
		  {name: Felsabers, wcm: [Felsabers]},
		  {name: Infernals, wcm: [Infernals]},
		  {name: "Ur'zul", wcm: ["Ur'zul"]},
		]
	},
	{ name: Devourer,
    subfamily: [
		  {name: Animite, wcm: [Animites]},
      {name: Gorger, wcm: [Anima Gorgers]},
      {name: Mauler, wcm: [Devourer Maulers]},
		]
	},
	{ name: Dinosaurs,
    subfamily: [
		  {name: Brutosaurs, wcm: [Brutosaurs]},
		  {name: Direhorns, wcm: [Direhorns]},
			{name: Falcosaurs, wcm: [Raptors], icons: [falcosauro]},
			{name: Pterrordaxes, wcm: [Pterrordaxes]},
			{name: Raptors, wcm: [Raptors, Undead Raptors], icons: [raptor]},
		]
	},
	{ name: Dragonhawks, wcm: [Dragonhawks] },
	{name: Drakes,
    subfamily: [
      {name: Cloud Serpents, wcm: [Cloud Serpents]},
      {name: Drakes, wcm: [Drakes, Onyxian Drakes, Void Dragons]},
      {name: Grand Drakes, wcm: [Grand Drakes]},
      {name: Nether Drakes, wcm: [Nether Drakes]},
      {name: Others, wcm: [Sinuous Drakes, Fey Drakes, Everwyrms, Mechanical Dragons, Greatwyrms], ids: [1563, 1590, 1591]}, # Highland Drake, Velocidrake, Cliffside Wylderdrake
      {name: Proto-Drakes, wcm: [Proto-Drakes], ids: [1589]}, # Renewed Proto Drake
      {name: Stone Drakes, wcm: [Stone Drakes]},
      {name: Undead Drakes, wcm: [Undead Drakes, Soul Eaters]},
      {name: Wind Drakes, wcm: [Wind Drakes]},
		]
  },
	{name: Elementals,
    subfamily: [
		  {name: Core Hounds, wcm: [Core Hounds]},
		  {name: Phoenixes, wcm: [Phoenixes]},
		  {name: Sabers, wcm: [Flamesabers]},
		  {name: Stone Drakes, wcm: [Stone Drakes]},
		  {name: Wind Drakes, wcm: [Wind Drakes]},
		  {name: Others, wcm: [Elementals, Ancients]},
		]
	},
	{name: Feathermanes,
    subfamily: [
		  {name: Gryphons, wcm: [Gryphons, Undead Gryphons]},
		  {name: Hippogryphs, wcm: [Hippogryphs]},
		  {name: Larion, wcm: [Larions]},
		  {name: Wolfhawks, wcm: [Wolfhawks]},
		  {name: Wyverns, wcm: [Wind Riders, Undead Wind Riders]},
		]
	},
	{name: Fish,
    subfamily: [
		  {name: Fish, wcm: [Fish]},
		  {name: Seahorses, wcm: [Seahorses, Hippocampuses]},
		  {name: Stingrays, wcm: [Stingrays]},
		]
	},
	{name: Gargoyle, wcm: [Gargoyles]},
	{name: Horses,
    subfamily: [
			{ name: Chargers,
        wcm: [Horses],
        icons: [_paladinmount_, _charger, nature_swiftness, alliancepvpmount, vicioushorse, paladin_divinesteed, horsekultiran, hordehorse],
        ids: [
				  341, # Argent Warhorse
					344, # Crusader's White Warhorse
					345, # Crusader's Black Warhorse
				]
			},
      { name: Demonic Steeds,
        wcm: [Demonic Steeds],
        ids: [
					898, # Netherlord's Chaotic Wrathsteed
					930, # Netherlord's Brimstone Wrathsteed
					931, # Netherlord's Accursed Wrathsteed
				]
			},
			{name: Flying Steeds, wcm: [Flying Steeds]},
			{name: Horned Steeds, wcm: [Horned Steeds, Windsteeds]},
			{name: Mechanical Steeds, wcm: [Mechanical Steeds]},
			{name: Mountain Horses,
        wcm: [Horses],
        icons: [dressedhorse, horse3],
        ids: [
					435, # Mountain Horse
					436, # Swift Mountain Horse
				]
			},
			{name: Steeds, wcm: [Horses], icons: [ridinghorse, nightmarehorse]},
			{name: Undead Steeds, wcm: [Undead Steeds]},
		]
	},
	{name: Humanoids,
    subfamily: [
			{name: Gronnlings, wcm: [Gronnlings]},
			{name: Gorger, wcm: [Anima Gorgers]},
			{name: Yetis, wcm: [Yeti]},
			{name: Others, ids: [1312]},
		]
	},
	{name: Insects,
    subfamily: [
			{name: Animite, wcm: [Animites]},
			{name: Aqir Flyers, wcm: [Aqir Flyers]},
			{name: Gorm, wcm: [Gorms]},
                      #   ids: [# somehow WCM has currently wrong mount ids for gorm
                      #       334364, # Spinemaw Gladechewer
                      #       312763, # Darkwarren Hardshell
                      #       334365, # Pale Acidmaw
                      #       340503, # Umbral Scythehorn
                      #       348769, # Vicious War
                      #       348770, # Vicious War Gorm
                      #       352441, # Wild Hunt Legsplitter
      		{name: Flies, wcm: [Flies, Skitterflies]},
			{name: Krolusks, wcm: [Krolusks]},
			{name: Moth, wcm: [Moths]},
			{name: Others, wcm: [ Bees, Ravagers ], ids: [1662] }, # Telix
			{name: Silithids, wcm: [Silithids],
        ids: [
					936, # Red Qiraji War Tank
					935, # Blue Qiraji War Tank
				]},
      {name: Water Striders, wcm: [Water Striders]},
      {name: Wasp, wcm: [Wasps]},
		]
	},
	{name: Jellyfish, wcm: [Fathom Dwellers, Hiveminds, Aurelids]},
	{name: Mollusc,
		subfamily: [
			{name: Snail, wcm:  [Snails]},
			{name: Slug, wcm:  [Slugs]},
	]},
	{name: Rats, wcm: [Rats, Mawrats]},
	{name: Rays,
    subfamily: [
			{name: Fathom Rays, wcm: [Fathom Rays]},
			{name: Mana Rays, wcm: [Mana Rays]},
			{name: Nether Rays, wcm: [Nether Rays]},
			{name: Stingrays, wcm: [Stingrays]},
		]
	},
	{name: Razorwing, wcm: [Razorwings]},
	{name: Reptiles,
    subfamily: [
			{name: Basilisks, wcm: [Basilisks]},
			{name: Crocolisks, wcm: [Crocolisks]},
			{name: Kodos, wcm: [Kodos], ids: [225]}, #Brewfest Riding Kodo
			{name: Mushan, wcm: [Mushan]},
			{name: N'Zoth Serpents, wcm: [N'Zoth Serpents]},
			{name: Sea Serpents, wcm: [Sea Serpents]},
			{name: Snapdragons, wcm: [Snapdragons]},
			{name: Shardhides, wcm: [Shardhides]},
			{name: Turtles, wcm: [Dragon Turtles, Sea Turtles, Turtles]},
			{name: Others, wcm: [Warp Stalkers, Armoredons, Newts], ids: [1639]}, # Lizi
		]
	},
	{name: Rylaks, wcm:  [Rylaks, Chimaeras]},
	{name: Ungulates,
    subfamily: [
			{name: Alpacas, wcm: [Alpacas]},
			{name: Boars, wcm: [Boars, Divine Boars, Skullboars]},
			{name: Camels, wcm: [Camels]},
			{name: Cervid, wcm: [Cervids] },
			{name: Elekks, wcm: [Elekks]},
			{name: Mammoths, wcm: [Mammoths]},
			{name: Moose, wcm: [Elderhorns, Bruffalons]},
			{name: Ox, wcm: [Oxen]},
			{name: Rhinos, wcm: [Rhinos]},
			{name: Riverbeasts, wcm: [Riverbeasts]},
			{name: Runestag, wcm: [Runestags]},
		]
	},
	{name: Vehicles,
    subfamily: [
			{name: Airplanes, wcm: [Airplanes]},
			{name: Airships, wcm: [Skyships, Zeppelins, Flying Ships]},
			{name: Assault Wagons, wcm: [Assault Wagons]},
			{name: Book, wcm: [Books]},
			{name: Carpets, wcm: [Flying Carpets]},
			{name: Discs, wcm: [Discs]},
			{name: Gyrocopters, wcm: [Gyrocopters]},
			{name: Hands, wcm: [Undead Hands]},
			{name: Hovercraft, wcm: [Hovercraft]},
			{name: Jet Aerial Units, wcm: [Jet Aerial Units]},
			{name: Kites, wcm: [Kites, Gliders]},
			{name: Mecha-suits, wcm: [Flying Mecha-suits]},
			{name: Mechanical Animals, wcm: [Mechanical Scorpions, Mechanical Steeds, Mechanical Birds, Mechanical Cats, Mechanical Dragons]},
			{name: Mechanostriders, wcm: [Mechanostriders]},
			{name: Motorcycles, wcm: [Motorcycles, Monocycles]},
			{name: Rockets, wcm: [Rockets]},
			{name: Seat, wcm: [Flying Seats]},
			{name: Spider Tanks, wcm: [Spider Tanks, Flying Spider Tanks]},
		]
	},
	{name: Vombata, wcm: [Wombats], icons: [progenitorwombat]},
	{name: Wolves,
    subfamily: [
			{name: Dire Wolves, wcm: [Wolves], icons: [wolfdraenor, orcclanworg], ids: [657]}, # Garn Nighthowl
			{name: Lupine, wcm: [Wolves], icons: [progenitorwolf, vicioushordewolf, viciousalliancewolf]},
			{name: Undead Wolves, wcm: [Undead Wolves]},
			{name: War Wolves, wcm: [Wolves], icons: [_hordepvpmount, _alliancewolf, armoredwolf, frostwolfhowler], ids: [306421]}, # Frostwolf Snarler
			{name: Wilderlings, wcm: [Wilderlings]},
			{name: Wolves, wcm: [Wolves], icons: [direwolf], ids: [51]}, # Arctic Wolf
		]
	},
]